[functions]
directory = "functions"

[[redirects]]
from = "/test/*"
to = "/.netlify/functions/test"
status = 200
force = true

[[redirects]]
from = "/mcq-get/*"
to = "/.netlify/functions/mcq-get"
status = 200
force = true

[[redirects]]
from = "/mcq-post/*"
to = "/.netlify/functions/mcq-post"
status = 200
force = true

[[redirects]]
from = "/request/*"
to = "/.netlify/functions/request"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/"
status = 200
